#!/bin/bash

all_name='[ALL]'
mode=spotify

d_artist() {
    mpc list artist | sort -f | dmenu -p artist "${dmenu_args[@]}"
}

d_album() {
    local artist="$1"
    local albums

    mapfile -t albums < <(mpc list album artist "$artist")
    if (( ${#albums[@]} > 1 )) ; then
        {
            printf '%s\n' "$all_name"
            printf '%s\n' "${albums[@]}" | sort -f
        } | dmenu -p album "${dmenu_args[@]}"
    else
        # We only have one album, so just use that.
        printf '%s\n' "${albums[0]}"
    fi
}

d_playlist() {
    local format="%position% - %title% - %album% - %artist%"
    local track

    track=$(mpc playlist -f "$format" | dmenu -p track "${dmenu_args[@]}")
    printf '%s' "${track%% *}"
}

d_spotify_playlist() {
	local playlist
	playlist=$(mpc lsplaylists | dmenu -p Playlist: "${dmenu_args[@]}")
	printf '%s' "${playlist}"
}
d_spotify_track() {
	local format="%position% - %title% - %artist%"
	local track
	track=$(mpc playlist -f "$format"| dmenu -p Track "${dmenu_args[@]}")
	printf '%s' "${track%% *}"
}
d_spotify_swap_menu() {
	local view
	view=$(echo -e "Change Playlist\nChange Song" | dmenu -p Menu: "${dmenu_args[@]}")
	printf '%s' "${view}"
}

i=3

for arg do
    if [[ $arg == :: ]]; then
        dmenu_args=( "${@:$i}" )
        break
    fi

    case "$arg" in
        -l) mode=library ;;
        -p) mode=playlist ;;
        -s) mode=spotify ;;
    esac

    let i++
done

case "$mode" in
    spotify)
	if [[ "$(d_spotify_swap_menu)" == "Change Playlist" ]]; then
		" Cache selection, preventing interrupting song while selecting new playlist"
		selectedtrack=$(d_spotify_playlist)
		mpc clear
		mpc load "$selectedtrack"
		mpc play 1
	else
		mpc play "$(d_spotify_track)"
	fi
	;;
    library)
        artist=$(d_artist)
        [[ $artist ]] || exit 1

        album=$(d_album "$artist")
        [[ $album ]] || exit 2

        mpc clear
        if [[ $album == "$all_name" ]]; then
            mpc find artist "$artist" | sort | mpc add
        else
            mpc find artist "$artist" album "$album" | sort | mpc add
        fi

        mpc play >/dev/null 2>&1
    ;;
    playlist)
        mpc play "$(d_playlist)"
    ;;
esac
